name: Check Senate Votes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_votes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack-sdk lxml beautifulsoup4 requests  

      - name: Run the script
        env:
          SLACK_API_KEY: ${{ secrets.SLACK_API_KEY }}  # Ensure your Slack API token is stored as a secret
        run: |
          python senate.py